# Generated by Django 4.2 on 2023-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="caffeine_today",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
