# Generated by Django 4.2 on 2023-09-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caffeineintake",
            name="type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
