# Generated by Django 4.2 on 2023-09-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_caffeineintake_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caffeineintake",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
