# Generated by Django 4.2 on 2023-09-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_caffeineintake_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="caffeineintake",
            name="caffeine",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
