# Generated by Django 4.0.6 on 2023-11-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_caffeineintake_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffeineintake',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
